version: '3.8'

services:
  # Traefik reverse proxy
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Backend
  auth-dev: # Flask
    build:
      context: py/
      dockerfile: Dockerfile.poetry
      target: development
      args:
        PROJECT_DIR: projects/auth
    stop_signal: SIGINT
    ports:
      - 5001:5000
    volumes:
      - ./py/projects/auth/auth:/app
    env_file:
      - ./py/projects/auth/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`)"
      - "traefik.http.routers.auth.rule=PathPrefix(`/login`)"

  import-dev: # Flask
    build:
      context: py/
      dockerfile: Dockerfile.poetry
      target: development
      args:
        PROJECT_DIR: projects/import
    stop_signal: SIGINT
    ports:
      - 5002:5000
    volumes:
      - ./py/projects/import/import:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.import.rule=Host(`localhost`)"
      - "traefik.http.routers.import.rule=PathPrefix(`/import`)"
